import { useState } from 'react'
import Icon from './Icon'
import { suggestedRules } from '../data/mockData'

export default function ConfigPage({ onNotify }) {
  const [tab, setTab] = useState('templates')
  const [rules, setRules] = useState({ flexibleSeries: true, strictKeys: true, optativeAuthorization: true, automaticWarnings: true })
  return (
    <div className="mx-auto max-w-[1350px] px-4 py-7 sm:px-6 lg:px-8">
      <p className="text-xs font-semibold uppercase tracking-[0.16em] text-blue-700">Administración</p><h2 className="mt-1 text-2xl font-bold tracking-tight text-slate-950">Configuración académica</h2><p className="mt-2 text-sm text-slate-500">Plantillas de reglas y comportamientos visibles en la experiencia de gestión.</p>
      <div className="mt-6 grid gap-5 lg:grid-cols-[220px_1fr]">
        <nav className="self-start rounded-2xl border border-slate-200 bg-white p-2 shadow-sm">{[['templates', 'Plantillas por nivel', 'layers'], ['rules', 'Reglas generales', 'settings'], ['exceptions', 'Excepciones', 'alert']].map(([id, label, icon]) => <button key={id} type="button" onClick={() => setTab(id)} className={`flex w-full items-center gap-2 rounded-xl px-3 py-2.5 text-left text-xs font-semibold ${tab === id ? 'bg-[#173b69] text-white' : 'text-slate-600 hover:bg-slate-50'}`}><Icon name={icon} size={14} />{label}</button>)}</nav>
        <main>
          {tab === 'templates' && <div className="grid gap-4 sm:grid-cols-2">{Object.entries(suggestedRules).map(([level, rule]) => <article key={level} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-wide text-blue-700">Plantilla vigente</p><h3 className="mt-1 text-base font-bold text-slate-900">{level}</h3></div><span className="rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-bold text-emerald-700 ring-1 ring-emerald-200">v1.0</span></div><div className="mt-5 grid grid-cols-2 gap-2">{[['Ciclos', rule.cycles], ['Semanas', rule.weeks], ['Créditos', `${rule.minCredits}–${rule.maxCredits}`], ['Horas mín.', rule.minHours.toLocaleString()], ['Materias/ciclo', rule.maxSubjects], ['Créditos/ciclo', rule.maxCycleCredits]].map(([label, value]) => <div key={label} className="rounded-xl bg-slate-50 p-3"><p className="text-[9px] font-semibold text-slate-400">{label}</p><p className="mt-1 text-sm font-extrabold text-slate-800">{value}</p></div>)}</div><button type="button" onClick={() => onNotify(`Se creó un borrador de nueva versión para ${level}.`)} className="mt-4 flex h-9 w-full items-center justify-center gap-2 rounded-xl border border-slate-200 text-[11px] font-semibold text-slate-600 hover:bg-blue-50 hover:text-blue-700"><Icon name="copy" size={13} /> Crear nueva versión</button></article>)}</div>}
          {tab === 'rules' && <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="text-base font-bold text-slate-900">Comportamiento de validaciones</h3><p className="mt-1 text-xs text-slate-500">Estos controles son locales para el prototipo.</p><div className="mt-5 divide-y divide-slate-100">{[['flexibleSeries', 'Prohibir seriaciones en planes flexibles', 'Evita prerrequisitos en modalidad no escolarizada cuando la plantilla lo indica.'], ['strictKeys', 'Validar claves contra posición visual', 'Muestra diferencias entre el mnemónico + posición y la clave registrada.'], ['optativeAuthorization', 'Exigir autorización en optativas', 'Solicita motivo y responsable si no se alcanzan las horas mínimas.'], ['automaticWarnings', 'Validación reactiva', 'Recalcula advertencias después de mover o editar una asignatura.']].map(([key, label, description]) => <label key={key} className="flex cursor-pointer items-center gap-4 py-4"><span className="flex-1"><span className="block text-xs font-bold text-slate-800">{label}</span><span className="mt-1 block text-[10px] text-slate-500">{description}</span></span><input type="checkbox" className="sr-only" checked={rules[key]} onChange={(e) => setRules((current) => ({ ...current, [key]: e.target.checked }))} /><span className={`relative h-6 w-11 rounded-full transition ${rules[key] ? 'bg-blue-600' : 'bg-slate-300'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow transition ${rules[key] ? 'left-6' : 'left-1'}`} /></span></label>)}</div></section>}
          {tab === 'exceptions' && <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h3 className="text-base font-bold text-slate-900">Excepciones autorizadas</h3><p className="mt-1 text-xs text-slate-500">Historial demostrativo con motivo, responsable y fecha.</p></div><button type="button" className="rounded-xl bg-[#173b69] px-3 py-2 text-[11px] font-semibold text-white">Nueva autorización</button></div><div className="mt-5 space-y-3">{[['Optativa debajo de horas mínimas', 'Narrativas interactivas', 'Dra. Laura Medina', '18 sep 2026'], ['Duración extraordinaria del plan', 'Arquitectura — 10 semestres', 'Consejo Académico', '04 sep 2026']].map(([type, item, owner, date]) => <article key={type} className="rounded-xl border border-amber-200 bg-amber-50/60 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-wide text-amber-700">{type}</p><p className="mt-1 text-xs font-bold text-slate-900">{item}</p><p className="mt-1 text-[10px] text-slate-500">Responsable: {owner} · {date}</p></div><span className="rounded-full bg-white px-2 py-1 text-[9px] font-bold text-emerald-700 ring-1 ring-emerald-200">Activa</span></div></article>)}</div></section>}
        </main>
      </div>
    </div>
  )
}
